apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: cars-virtual-router
  namespace: car-mircoservices-app
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: cars-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - vitualNodeRef:
                name: car-service-virtual-node
              weight: 1